# Generated by Django 6.1.1 on 2026-09-22 14:16

import django.db.models.deletion
import receipts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_original', models.FileField(upload_to='receipts/%Y/%m/')),
                ('fecha_emision', models.CharField(blank=True, max_length=20)),
                ('cuit_emisor', models.CharField(blank=True, max_length=11)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=50)),
                ('letra', models.CharField(blank=True, max_length=5)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50)),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('importe_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('categoria_gasto_siradig', models.CharField(blank=True, max_length=100)),
                ('origen', models.CharField(choices=[('telegram', 'Telegram'), ('upload_web', 'Carga manual (web)')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_revision', 'Pendiente de revisión'), ('pendiente_carga', 'Pendiente de carga en SIRADIG'), ('cargado_en_siradig', 'Cargado en SIRADIG')], default='pendiente_revision', max_length=20)),
                ('raw_ocr_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('telegram_link_token', models.CharField(default=receipts.models._generate_token, max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
